### ISSUE TITLE
invalid number error

### ISSUE THREAD

**Issue by MattPark** [sandain/MinecraftServerControlScript#65] opened 2014-12-27 19:16 UTC
So for me, server status isn't working.  All the commands that invoke status in some way, run into an issue with "invalid number".

It's because 08 and 09 are interpreted as invalid octal numbers, and when you try to printf them into your status commands, it causes a failure.

I tried to force it to cast them as decimal by evaluating as $(( 10#09 )) but it's not working.

I also tried switching the shells from /bin/sh to /bin/bash but that creates a lot more errors.  Not sure how best to resolve this

**Comment by MattPark** [comment] 2015-01-05 18:28
Short answer no, it doesn't seem to do it.
```
[~]
[root@nas]# /opt/bin/bash -c "echo $(printf "%d" $(echo 99))"
99
[~]
[root@nas]# /opt/bin/bash -c "echo $(printf "%d" $(echo 09))"
bash: printf: 09: invalid number
0
[~]
[root@nas]# /opt/bin/bash -c "echo $(printf "%d" $(echo 07))"
7
[~]
[root@nas]# /opt/bin/bash -c "echo $(printf "%d" $(echo 08))"
bash: printf: 08: invalid number
0
[~]
[root@nas]#
```

**Comment by sandain** [comment] 2015-01-05 19:55
I'm not totaly sure what I'm seeing here.  I would expect all of those to fail or succeed in the same way, especially those that have a leading zero.

This may be related to the way you are doing the quoting: the `%d` is probably not being quoted when it reaches the printf statement.  Try swapping the outer double quotes with single quotes for a better test:
```
/opt/bin/bash -c 'echo $(printf "%d" $(echo 99))'
/opt/bin/bash -c 'echo $(printf "%d" $(echo 09))'
/opt/bin/bash -c 'echo $(printf "%d" $(echo 08))'
/opt/bin/bash -c 'echo $(printf "%d" $(echo 07))'
```

**Comment by MattPark** [comment] 2015-01-06 19:04
Same result:
[~]
[root@nas]# /opt/bin/bash -c 'echo $(printf "%d" $(echo 99))'
99
[~]
[root@nas]# /opt/bin/bash -c 'echo $(printf "%d" $(echo 09))'
/opt/bin/bash: line 0: printf: 09: invalid number
0
[~]
[root@nas]# /opt/bin/bash -c 'echo $(printf "%d" $(echo 08))'
/opt/bin/bash: line 0: printf: 08: invalid number
0
[~]
[root@nas]# /opt/bin/bash -c 'echo $(printf "%d" $(echo 07))'
7

**Comment by MattPark** [comment] 2015-01-06 20:10
So on line 1442, you're building a string from some variables.  $2 is sometimes "09" from line 1483.  Couldn't you just use "0" and "9" and concatenate them for that case?  Or just use a 9 and then set your printf statement on 1442 to use 0 padding?

**Comment by sandain** [comment] 2015-01-13 20:27
Sorry, I've been busy and haven't had time to give this much thought.  I get the same result as you when I run the code snippet in my last post... I guess I should test things first!

Anyway, it looks like there is an issue with a string being interpreted as an octal number as you stated earlier.  When I get a chance, I'll take another look at this to see if I can figure out where it is happening.  Right now I'm too busy though. =/

**Comment by MattPark** [comment] 2015-01-14 14:47
No problem --- I have a workaround in place that works better than
expected, so no rush on this end.

**Comment by jjchico** [comment] 2015-08-03 17:15
The whole problem reduces to removing the leading zeroes read by queryStatus so that the number is not interpreted as an octal number by the shell. It can be done using 'sed':

    queryStatus $WORLD | cut -f6 | sed 's/^0*//'

Maybe a good general solution would be to convert every number queried by queryStatus and queryDetailedStatus inside the functions.

**Comment by MattPark** [comment] 2015-08-04 04:18
Nice---- did this actually work?  Or theoretical?  I ended up creating a Debian chroot environment and running it in there. I still don't get why can't I just cast the octal to dec...

**Comment by jjchico** [comment] 2015-08-04 10:19
This is an idea, but it should work. I'll implement it when I have a minute and give you a branch so you can test.
It is not a casting problem. printf "%d" will happily cast any octal number like in:

    $ printf "%d\n" 010
    8
The problem is that "08" is formatted like octal but uses illegal octal digits. There is no cast to do here because there is no valid value to assign to '08' according to shell syntax. That is why I propose to convert the numbers to the right syntax as soon as they are received from the server.
Stay tuned.

**Comment by sandain** [comment] 2015-08-04 16:48
My guess is that the issue happens in the queryStatus and queryDetailedStatus methods.  Both methods have a printf statements that might be the cause:
```
PACKET=$(printf "%.8x" $TOKEN)
PACKET=$(printf "%.8x%.8x" $TOKEN $ID)
```

The printf statements in the querySendPacket method that aren't written in perl, utilize strings which I assume would be less of an issue:
```
PACKET=$(printf "FEFD%s%s%s" "$2" "$ID" "$3")
```

The easiest patch that I see might just be wrapping $TOKEN and $ID in quotes in those two methods.  The other option might be to replace `%.8x` with `%s`, but I seem to remember wanting the formatted output for some reason.

**Comment by jjchico** [comment] 2015-08-05 09:29
I have debugged the responses of the query* functions and I do not see any issues with the returned number format. Matt: Have you tried the current version of mscs?
In any case, I have proposed a patch to simplify the query of the number of users that eliminates the "printf" step so it may help solving this issue.
Matt: can you test the patch?
https://github.com/jjchico/MinecraftServerControlScript/tree/query-fixes

**Comment by MattPark** [comment] 2015-08-08 23:56
For me the error only happens on some platforms--
I will test it it a few days

**Closed** 2015-11-04 18:22 UTC
