### ISSUE TITLE
Extra Function

### ISSUE THREAD

**Issue by JimTR** [sandain/MinecraftServerControlScript#85] opened 2015-08-01 13:30 UTC
I am thinking of producing a function for the script that could be run as a cron job, basically this will check if a world is running if the the return from that if null start the world. Reason I need to do this is on Ubuntu 12.04 after a day or so the script dies. using a 'monito'r function via cron could attempt to restart without intervention. I would guess there is an 'is_world_running' function (to date I have not get my head around the script) and there has to be a start function. Can you give me the function names so it saves me reinventing them. Other observations if you run the script on a VPS running Plesk (to  manage domains) the minecraft server is found by all domains attached i.e domain1.com & domain2.com (entered in the minecraft launcher) finds the same instance, I expect this to be the minecraft launcher translating the domain name to it's IP (no problem with the script perhaps) but you may get this as a bug from users who install the script on a multi domain VPS.

**Comment by sandain** [comment] 2015-08-02 20:04
If you are going to create an external script that calls mscs; see the `ls stopped` command, it is approximately what you need for your cron job.  The actual function inside the script is called `serverRunning`.

If you are trying to understand the script, it actually starts at about line 1773 after all of the functions have been defined.  The function that actually starts the server is called `start`, but it calls a number of other functions like `updateServerSoftware`, `execute`, `rotateLog`, etc.  The `execute` command is just a little trick to make sure that `root` isn't running the command but the `minecraft` user is instead.

I'm not sure what you are talking about with the domain names.  I don't think the script will have any issues working on the VPS, but I can work with you on fixing any errors that do come up.

**Comment by JimTR** [comment] 2015-08-03 08:22
Thanks for the reply I have set up a test server on a multi domain server so you can see what I am talking about. load the following servers (without port assignment) into the minecraft launcher noideersoftware.co.uk yamahahbikersclub.com ickleh.co.uk you will find that all of the above will run the same instance of  minecraft. I am not to worried about it but my customers (the other domains on the plesk server) my not like it. With plesk (control panel) when a new domain is created the user is 'jailed' to their vhost so can you foresee a problem of adding multiple versions of mscs in their jail ?
example /var/www/vhosts/domain.com (this is the jail directory) /opt/mscs using this method allows all the correct permissions to the mscs script to the plesk user. just so you can see it the web interface looks like this (currently)
![image](https://cloud.githubusercontent.com/assets/4038510/9033674/343fdb60-39c1-11e5-81eb-b3a2a4747931.png)

**Comment by zanix** [comment] 2015-08-03 15:06
I don't think multiple instances of the mscs script would be a problem.
You would need a copy of the mscs script probably somewhere in each users' jail `/home/username/mscs/*` and the preferences file (`/etc/default/mscs`) there as well. You would probably also need to edit each instance of the script to load preferences from other than `/etc/default/mscs`.

**Comment by JimTR** [comment] 2015-08-05 20:28
Thanks ....on a plesk server the user is not given a home directory, if the user is not allowed ssh login the only access they have is to /var/www/domain_name.tld/, and they can only see via ftp  /var/www/domain_name.tld/httpdocs/ but can access  /var/www/domain_name.tld/

**Comment by sandain** [comment] 2015-08-06 04:27
I think I understand the issue.

It sounds to me like the problem is that you have a single machine with multiple URL assigned to it but only a single network interface/IP address.  Now if the each of those URL were assigned to a different IP address and those different IP address were to each have their own network interface, I think there is something we could do (the server.properties file has the option to bind to an IP address, we usually recommend not using that option since it complicates things).

The script handles running multiple worlds by using different ports, but this doesn't help if each one of your domain users expects to find their own minecraft world on the default port.  I think what you would need is a BungeeCord like proxy server listening to the default port, but serving up the world based on the domain name.  I don't know if BungeeCord can handle such a setup or not, but it is where I would start looking.

**Comment by zanix** [comment] 2015-08-06 14:43
You can use SRV records to help with this.
http://www.minecraftforum.net/forums/support/server-support/tutorials-and-faqs/1940461-using-srv-records-to-hide-ports-on-your-server-ip

Most DNS provider have the ability to add SRV records and if your's does not, I know namecheap does (it's what i use).

With this, you can set up SRV records using subdomains for each domain you have to point to the different ports on this single server. this also means that users will never need to know which port to connect to.
```
_minecraft._tcp.domain.name. 86400 IN SRV 0 5 25566 server.domain.name.
```

I have one IP address and domain but use multiple subdomains for the minecraft servers I host.
```
survival.domain.com
snapshot.domain.com
tfc.domain.com
...
```

**Comment by sandain** [comment] 2015-08-06 16:02
that is a better solution, I didn't think of using SRV records.

**Comment by JimTR** [comment] 2015-08-07 18:21
just a thought have you used plesk ?

**Comment by zanix** [comment] 2015-08-07 18:32
Not for quite a number of years.

**Comment by sandain** [comment] 2015-08-07 19:41
I haven't used it

**Comment by jjchico** [comment] 2015-08-08 07:28
@JimTR If your servers go down after a few days it is not a problem of the control script, that only runs at server start-up. Have you checked your server logs at <world>/logs?
Does your servers die (the java process exits) or does they simply hang up? If the java process dies you may restart it just doing a "mscs start <world>". If the world is already running, the "start" will do nothing, so you do not really need to check if your server died or not. So e.g. if you want to be sure your server "alpha" is restarted if it dies, just write a script like this:

    #!/bin/sh
    mscs start alpha

an put it in /etc/cron.daily or /etc/cron.hourly.

But you better find out what is the reason your servers die.

**Comment by JimTR** [comment] 2015-08-08 11:52
I have no clue why it failed as the log file  /opt/mscs/world/log/latest.log (assuming that this if the file I should be looking at)  contains no clues... however after updating to 1.88 minecraft server software the server has now run for 5 days without a problem ... maybe the 1.87 version had a slight bug in it ... I will add a craftbukkit server (1.87) to see if this fails in the same way as the std mc server did which may or may not confirm this was the issue. I would have thought I could just add the command line to the cron entry rather than writing a script    such as
*/5     *       *       *       *       -u nod /var/www/vhosts/nod.co.uk/httpdocs/mscs/mscs start world 
should do the trick ?

**Comment by jjchico** [comment] 2015-08-10 21:26
I do not think that "-u nod" is the right syntax in case you want to execute mscs as user nod. At least in Debian-like systems if you want to execute something that often you should install a snippet in /etc/cron.d. Create a file "mscs" in /etc/cront.d like:

    # /etc/cron.d/mscs: crontab entries for mscs
    
    SHELL=/bin/sh
    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

    */5 *    * * *   nod	/var/www/vhosts/nod.co.uk/httpdocs/mscs/mscs start world

**Closed** 2015-11-04 18:22 UTC
Labels: question
