### ISSUE TITLE
Error, the eula has not been accepted

### ISSUE THREAD

**Issue by ronald245** [sandain/MinecraftServerControlScript#97] opened 2015-08-20 14:56 UTC
i've been having some issues in porting my windows-based server to linux.

i have managed to get one world in my bungeecord to start but when the second one starts it tells me the eula hasnt been accepted, 
when i open the file in nano/leafpad both of them show the eula=true 

what am i doing wrong or can i fix this script-wise?

**Comment by sandain** [comment] 2015-08-20 15:59
After looking at the code, I found a potential issue:
The `getEULAValue()` method uses the `getValue()` method to parse key/value pairs, but the `getValue()` method only ensures that the key is lowercase, the value is left as is.  The EULA error is printed if the value is not exactly equal to `true`, so `eula=TRUE` won't work, but `EULA=true` probably does.  I don't think spaces are allowed either, so `eula = true` probably won't work.

Can you post a copy of your eula.txt file that is giving the problem?

These methods can probably be cleaned up to support the same values that the Minecraft server itself supports, I would just need to run some tests to see what it accepts as far as spaces and uppercase are concerned.

There is one other thing you can check:  Windows uses different line endings in their text files than anyone else does.  They use the characters `CR+LF`, whereas everyone else uses just `LF`.  I'm guessing that the extra `CR` character is messing with the regular expressions.  Many decent text editors have the ability to save text files using either format (usually labelled DOS/Windows or UNIX), if yours does you can try to resave the file using the UNIX format line endings.

**Comment by ronald245** [comment] 2015-08-20 17:17
the eula.txt file:

#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
#Mon Jul 27 04:49:23 CEST 2015
eula=true

some additional information, i used leafpad on debian to edit the file
it seems that eula is in lowercase in my file, i'll try switching it to uppercase and report back

**Comment by sandain** [comment] 2015-08-20 19:13
All lower case as it is should work best.  If its not the CR+LF issue, then I'm at a loss for what the problem is.

**Comment by ronald245** [comment] 2015-08-20 19:36
Changing the line ending from CR+LF to LF fixed it, thanks a lot

**Comment by sandain** [comment] 2015-08-21 21:02
I'm glad that fixed it for you.  When I have the chance, I'll take a closer look at the code and I'll try to make it more robust.  I'm afraid this might be a whack-a-mole type of situation though, there are probably issues in a number of the regular expressions throughout the script.

**Comment by sandain** [comment] 2015-08-28 00:03
Closing this issue as fixed with commit 93dbb42ce37bc43ff32da31423577fdb57f89f86.

**Closed by sandain** 2015-08-28 00:03 UTC
